name: MoonstoneHub
version: 1.3.4 SNAPSHOT
author: WoMspace
main: net.womspace.moonstonehub.MoonstoneHub
api-version: 1.15
commands:
  hub:
    description: Sends the player to the hub.
    usage: /hub
  stop:
    description: Sends all players to the hub world and stops the current server.
    usage: /stop
  msg:
    description: Overrides the built-in /msg command to make it work with certain plugins.
    usage: /msg <Player> <Message>
  whisper:
    description: Overrides the built-in /msg command to make it work with certain plugins.
    usage: /msg <Player> <Message>
  tell:
    description: Overrides the built-in /msg command to make it work with certain plugins.
    usage: /msg <Player> <Message>
  map:
    description: Allows players to get the link to the map.
    usage: /map
permissions:
  moonstonehub.*:
    children:
      moonstonehub.hub: true
      moonstonehub.msg: true
      moonstonehub.stop: true
  moonstonehub.hub:
    description: Teleports you to the hubworld from another server.
    default: true
  moonstonehub.msg:
    description: Allows you to privately message another player.
    default: true
  moonstonehub.stop:
    description: Kicks all players to the hubworld and stops the server.
    default: op